### ISSUE TITLE
Libby-Bukkit Dependency size

### ISSUE THREAD

**Issue by ItsRainingHP** [AlessioDP/libby#36]
libby-bukkit dependency is over 6 mbs? Posting error for resolution hopefully. Developer is aware.

This is the only dependency in my pom.xml
```
        <dependency>
            <groupId>com.alessiodp.libby</groupId>
            <artifactId>libby-bukkit</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
```

![image](https://github.com/AlessioDP/libby/assets/79205731/63fc1a71-538a-4488-ba77-349c23c2db41)

It looks like the entire Bukkit API is inside the jar.
![image](https://github.com/AlessioDP/libby/assets/79205731/2d74b0d0-a2cd-4440-b280-df6bbbf2846c)

As suggested in the README file I do have the configuration section in maven-shade
```
                <configuration>
                    <relocations>
                        <relocation>
                            <pattern>com.alessiodp.libby</pattern>
                            <shadedPattern>com.mysite.libs.com.alessiodp.libby</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
```

**Comment by frengor** [comment]
I forgot to fix the `bukkit` module in a previous commit which fixed this for the other platforms.

**Comment by ItsRainingHP** [comment]
This commit has corrected the issue.
