### ISSUE TITLE
[Question] Where do you actually use this?

### ISSUE THREAD

**Issue by Andre601** [AlessioDP/libby#47]
I can't find an answer to this (probably simple) question, but where or *when* exactly would I set the loader, libraries, etc?

Would it be during the plugin's loading phase (`onLoad()`)? Enable phase (`onEnable()`)? Anywhere else?

**Comment by Andre601** [comment]
Figured it out. Put it in the onLoad() method.

I feel like the readme should mention this.

**Comment by frengor** [comment]
Libraries can be loaded at any time (even though usually the right choice is `onLoad()`). For example, in [UltimateAdvancementAPI](https://github.com/frengor/UltimateAdvancementAPI) libraries are loaded only when needed and before loading the classes requiring their presence (see [here](https://github.com/frengor/UltimateAdvancementAPI/blob/6b7a32660958df6a857afc2972558e982031c36b/Common/src/main/java/com/fren_gor/ultimateAdvancementAPI/database/impl/MySQL.java#L68) and [here](https://github.com/frengor/UltimateAdvancementAPI/blob/6b7a32660958df6a857afc2972558e982031c36b/Commands/Common/src/main/java/com/fren_gor/ultimateAdvancementAPI/commands/CommandAPIManager.java#L50)).

> I feel like the readme should mention this.

IIRC @AlessioDP was writing a wiki for the 2.0.0 version, however I don't know if it mentioned this.
