### ISSUE TITLE
Instructions for VelocityLibraryManager

### ISSUE THREAD

**Issue by Andre601** [AlessioDP/libby#48]
The VelocityLibraryManager seems to be a odd one out of the group for a few reasons, one of them being that you need to define the plugin's main class as part of it...

It would be good if instructions would be present for to make it easier to understand how to properly use it, because from what I understand is this what you're supposed to do?

```java
public class MyVelocityPlugin {
    
    @Inject // Maybe too early to call it in constructor?
    public MyVelocityPlugin(ProxyServer proxy, @DataDirectory Path path) {
        VelocityLibraryManager<MyVelocityPlugin> manager = new VelocityLibraryManager<>(
            this, LoggerFactory.getLogger(MyVelocityPlugin.class), path, proxy.getPluginManager()
        );
        
        // Do stuff...
    }
}
```

**Comment by AlessioDP** [comment]
Yes, that is the correct way to call it, the logger can be obtained with an argument in the Inject constructor:
```java
@Inject
public MyPlugin(Logger logger, @DataDirectory Path dataDirectory, PluginManager pluginManager) {
    VelocityLibraryManager<MyPlugin> libraryManager = new VelocityLibraryManager<>(this, logger, dataDirectory, pluginManager);
}
```

A wiki is planned to be published once the gradle branch is released.
