### ISSUE TITLE
Relocate imports in my plugin's jar

### ISSUE THREAD

**Issue by kangarko** [AlessioDP/libby#49]
Not sure if I am understanding it wrong but I am using the " relocate("package{}to{}relocate", "the{}relocated{}package")" feature however my plugin's jar still has the old package in it, crashing when the server loads.

Is it possible that this library will also relocate the libraries within the plugin it's used by?

Thanks.

**Comment by AlessioDP** [comment]
The relocate method is meant to be used to relocate the loaded library only.
What you are looking for is the relocation defined in your own pom.xml/gradle.

**Comment by kangarko** [comment]
Thanks.

Just like sometimes maven/gradle can't be used to relocate and so we use libby, sometimes I can't relocate my own jar using maven/gradle and I need to do it on runtime.

I thought libby will also scan my own plugin and relocate imports to the relocated libraries?

Is this possible? I know luckperms has "jarinjar", is that too difficult to add?

**Comment by frengor** [comment]
> I thought libby will also scan my own plugin and relocate imports to the relocated libraries?
>
> Is this possible? I know luckperms has "jarinjar", is that too difficult to add?

No, it is definitely too difficult (or even impossible) to do. One thing you can do however is creating a sub-jar of your plugin with all the classes to relocate and then load it using Libby in your main class. (Ideally, your plugin should only contain the main class and the subjar. The main class should just load the subjar and the business logic should be completely handled by the subjar)

**Comment by kangarko** [comment]
Thanks. I managed to work this around by using libby to load an older version of the library instead of this expensive rewrite. Appreciated your help!
